apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-cloud-public-profile
  description: GitHub Cloud profile visible for public users
  links:
  - url: https://github.com/sverigesradio?view_as=public
    title: Public profile
spec:
  type: website
  lifecycle: production
  owner: devcore
  system: GitHub
